# Generated by Django 4.1.7 on 2023-04-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=250, null=True, upload_to='room/'),
        ),
    ]
