# Generated by Django 4.1.7 on 2023-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_document_delete_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='semister',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
