# Generated by Django 4.1.7 on 2023-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullstack', models.CharField(default=True, max_length=200)),
                ('cybersecurity', models.CharField(default=True, max_length=200)),
                ('ai', models.CharField(default=True, max_length=200)),
                ('ml', models.CharField(default=True, max_length=200)),
                ('robotics', models.CharField(default=True, max_length=200)),
                ('datascience', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
