# Generated by Django 4.1.7 on 2023-04-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_links_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='program',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
