# Generated by Django 4.1.7 on 2023-04-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify',
            field=models.TextField(),
        ),
    ]
