# Generated by Django 4.1.7 on 2023-04-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_notification_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notify',
            new_name='notification',
        ),
    ]
