# Generated by Django 4.1.7 on 2023-04-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_rename_notify_notification_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification',
            new_name='notifications',
        ),
    ]
