# Generated by Django 4.1.7 on 2023-04-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_rename_notification_notification_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='notify',
        ),
        migrations.RenameField(
            model_name='notify',
            old_name='notifications',
            new_name='text',
        ),
    ]
